version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.5
    container_name: elk_elasticsearch
    restart: always
    environment:
      - "cluster.name=elasticsearch-spring"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    volumes:
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml 
    ports:
      - 9200:9200
  kibana:
    image: kibana:7.17.5
    container_name: elk_kibana
    restart: always
    depends_on:
      - elasticsearch 
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200 
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
  logstash:
    image: logstash:7.17.5
    container_name: elk_logstash
    restart: always
    volumes:
      - ./logstash/config/logstash-springboot.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:es
    ports:
      - 4560:4560


      
